on:
  push:
    branches:
      - master
    paths:
      - 'game/**'

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export and publish game
    steps:
    - name: checkout
      uses: actions/checkout@v2.0.0
    - name: export
      uses: firebelley/godot-export@v1.1.0
      with:
        base_version: 0.1.0
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2/Godot_v3.2-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2/Godot_v3.2-stable_export_templates.tpz
        godot_template_version: 3.2.stable
        relative_project_path: ./game
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: publish windows
      uses: josephbmanley/butler-publish-itchio-action@v1.0.0
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: windows
        ITCH_GAME: plague
        ITCH_USER: dsaltares
        PACKAGE: build/win
    - name: publish linux
      uses: josephbmanley/butler-publish-itchio-action@v1.0.0
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: linux
        ITCH_GAME: plague
        ITCH_USER: dsaltares
        PACKAGE: build/linux
    - name: publish mac
      uses: josephbmanley/butler-publish-itchio-action@v1.0.0
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: mac
        ITCH_GAME: plague
        ITCH_USER: dsaltares
        PACKAGE: build/mac
    - name: publish html5
      uses: josephbmanley/butler-publish-itchio-action@v1.0.0
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: html5
        ITCH_GAME: plague
        ITCH_USER: dsaltares
        PACKAGE: build/web
